version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    ports:
    - "50070:50070"
    - "9000:9000"
    - "8030:8030"
    - "8031:8031"
    - "8032:8032"
    networks:
      - workbench
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      # add placement constraint to allocate namenode on particular server
      #placement:
      #  constraints:
      #    - node.hostname == master.node.com
      labels:
        traefik.docker.network: workbench
        traefik.port: 50070

volumes:
  namenode:

networks:
  workbench:
    external: true
