version: '3'
services:
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    ports:
    - "50075:50075"
    networks:
      - workbench
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    deploy:
      # mode global will deploy one datanode per docker swarm node
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: workbench
        traefik.port: 50075

volumes:
  datanode:

networks:
  workbench:
    external: true
