version: '3'
services:
  hue:
    image: bde2020/hdfs-filebrowser:3.11
    ports:
    - "8092:8088"
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: workbench
        traefik.port: 8088
    environment:
      - NAMENODE_HOST=namenode
    networks:
      - workbench

  datascience-notebook:
    image: jupyter/pyspark-notebook
    volumes:
    - /home/jens/jupyter:/home/jovyan/work
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
    - "8888:8888"
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: workbench
        traefik.port: 8888
    networks:
      - workbench

volumes:
  zeppelinnotebooks:

networks:
  workbench:
    external: true
